services:
  localclaw:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    container_name: localclaw
    restart: unless-stopped
    environment:
      - OPENCLAW_ARGS=
    volumes:
      - ${HOME}/.openclaw/localclaw:/home/openclaw

  localclaw-lan:
    image: ${REGISTRY}/${IMAGE}:${VERSION}
    container_name: localclaw
    restart: unless-stopped
    profiles:
      - lan
    ports:
      - "18789:18789"
    environment:
      - OPENCLAW_ARGS=--allow-unconfigured --bind lan
    volumes:
      - ${HOME}/.openclaw/localclaw:/home/openclaw
